# ---------------------------------------------------------------------------
# "consenterOrgs" - Definition of organizations managing consenter nodes
# ---------------------------------------------------------------------------
consenterOrgs:
  # ---------------------------------------------------------------------------
  # consenter
  # ---------------------------------------------------------------------------
  - name: Consenter
    domain: example.com

    # ---------------------------------------------------------------------------
    # "specs" - See PeerOrgs below for complete description
    # ---------------------------------------------------------------------------
    specs:
      - hostname: consenter

# ---------------------------------------------------------------------------
# "nodeOrgs" - Definition of organizations managing node nodes
# ---------------------------------------------------------------------------
nodeOrgs:
  # ---------------------------------------------------------------------------
  # Org1
  # ---------------------------------------------------------------------------
  - name: Org1
    domain: org1.example.com
    enableNodeOUs: false

    # ---------------------------------------------------------------------------
    # "ca"
    # ---------------------------------------------------------------------------
    # Uncomment this section to enable the explicit definition of the CA for this
    # organization.  This entry is a Spec.  See "Specs" section below for details.
    # ---------------------------------------------------------------------------
    # ca:
    #    hostname: ca # implicitly ca.org1.example.com
    #    country: US
    #    province: California
    #    locality: San Francisco
    #    organizationalUnit: Hyperledger Fabric
    #    streetAddress: address for org # default nil
    #    postalCode: postalCode for org # default nil

    # ---------------------------------------------------------------------------
    # "specs"
    # ---------------------------------------------------------------------------
    # Uncomment this section to enable the explicit definition of hosts in your
    # configuration.  Most users will want to use Template, below
    #
    # Specs is an array of Spec entries.  Each Spec entry consists of two fields:
    #   - hostname:   (Required) The desired hostname, sans the domain.
    #   - commonName: (Optional) Specifies the template or explicit override for
    #                 the CN.  By default, this is the template:
    #
    #                              "{{.Hostname}}.{{.Domain}}"
    #
    #                 which obtains its values from the Spec.Hostname and
    #                 Org.Domain, respectively.
    #   - sans:       (Optional) Specifies one or more Subject Alternative Names
    #                 to be set in the resulting x509. Accepts template
    #                 variables {{.Hostname}}, {{.Domain}}, {{.CommonName}}. IP
    #                 addresses provided here will be properly recognized. Other
    #                 values will be taken as DNS names.
    #                 NOTE: Two implicit entries are created for you:
    #                     - {{ .CommonName }}
    #                     - {{ .Hostname }}
    # ---------------------------------------------------------------------------
    # specs:
    #   - hostname: foo # implicitly "foo.org1.example.com"
    #     commonName: foo27.org5.example.com # overrides Hostname-based FQDN set above
    #     sans:
    #       - "bar.{{.Domain}}"
    #       - "altfoo.{{.Domain}}"
    #       - "{{.Hostname}}.org6.net"
    #       - 172.16.10.31
    #   - hostname: bar
    #   - hostname: baz

    # ---------------------------------------------------------------------------
    # "template"
    # ---------------------------------------------------------------------------
    # Allows for the definition of 1 or more hosts that are created sequentially
    # from a template. By default, this looks like "node%d" from 0 to Count-1.
    # You may override the number of nodes (Count), the starting index (Start)
    # or the template used to construct the name (Hostname).
    #
    # Note: Template and Specs are not mutually exclusive.  You may define both
    # sections and the aggregate nodes will be created for you.  Take care with
    # name collisions
    # ---------------------------------------------------------------------------
    template:
      count: 1
      # start: 5
      # hostname: {{.Prefix}}{{.Index}} # default
      # sans:
      #   - "{{.Hostname}}.alt.{{.Domain}}"

    # ---------------------------------------------------------------------------
    # "users"
    # ---------------------------------------------------------------------------
    # count: The number of user accounts _in addition_ to Admin
    # ---------------------------------------------------------------------------
    users:
      count: 1

  # ---------------------------------------------------------------------------
  # Org2: See "Org1" for full specification
  # ---------------------------------------------------------------------------
  - name: Org2
    domain: org2.example.com
    enableNodeOUs: false
    template:
      count: 1
    users:
      count: 1